"""add reminder fields

Revision ID: 1ce3f97a46e9
Revises: 7c7497c81001
Create Date: 2026-08-09 17:00:38.045771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce3f97a46e9'
down_revision: Union[str, Sequence[str], None] = '7c7497c81001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_records', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reminders_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminders_enabled')
    op.drop_column('health_records', 'reminder_sent_at')
    # ### end Alembic commands ###
