"""add weight tracking columns

Revision ID: 58aa610b2ce0
Revises: 6323b3923c6a
Create Date: 2026-08-27 05:24:37.448604

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '58aa610b2ce0'
down_revision: Union[str, Sequence[str], None] = '6323b3923c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_records', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('pets', sa.Column('weight_tracking_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pets', sa.Column('weight_frequency', sa.String(length=10), server_default='monthly', nullable=False))
    op.add_column('users', sa.Column('weight_tracking_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_tracking_enabled')
    op.drop_column('pets', 'weight_frequency')
    op.drop_column('pets', 'weight_tracking_enabled')
    op.drop_column('health_records', 'weight_kg')
    # ### end Alembic commands ###
