"""add reminder frequency and drop dead columns

Revision ID: 6323b3923c6a
Revises: 72d97ce0e39a
Create Date: 2026-08-26 11:09:21.610896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6323b3923c6a'
down_revision: Union[str, Sequence[str], None] = '72d97ce0e39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_records', 'reminder_sent_at')
    op.drop_column('scheduled_events', 'reminder_sent_at')
    op.drop_column('scheduled_events', 'muted_until')
    op.drop_column('scheduled_events', 'confirmation_sent_at')
    op.add_column('users', sa.Column('reminder_frequency', sa.String(length=10), server_default='weekly', nullable=False))
    op.add_column('users', sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_enabled')
    op.drop_column('users', 'reminder_frequency')
    op.add_column('scheduled_events', sa.Column('confirmation_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('scheduled_events', sa.Column('muted_until', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('scheduled_events', sa.Column('reminder_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('health_records', sa.Column('reminder_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
