"""add record photos

Revision ID: 677fca779bac
Revises: fc3b4e5234b8
Create Date: 2026-08-17 21:11:26.815370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677fca779bac'
down_revision: Union[str, Sequence[str], None] = 'fc3b4e5234b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['health_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_photos_id'), 'record_photos', ['id'], unique=False)
    op.create_index(op.f('ix_record_photos_record_id'), 'record_photos', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_photos_record_id'), table_name='record_photos')
    op.drop_index(op.f('ix_record_photos_id'), table_name='record_photos')
    op.drop_table('record_photos')
    # ### end Alembic commands ###
