"""Add scheduled events

Revision ID: 72d97ce0e39a
Revises: c8c383d27377
Create Date: 2026-08-25 10:49:15.585148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d97ce0e39a'
down_revision: Union[str, Sequence[str], None] = 'c8c383d27377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('APPOINTMENT', 'RECORD_FOLLOWUP', 'WEIGHT_CHECKIN', name='eventkind'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('muted_until', sa.Date(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.Column('result_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_record_id'], ['health_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['health_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_events_due_date'), 'scheduled_events', ['due_date'], unique=False)
    op.create_index(op.f('ix_scheduled_events_id'), 'scheduled_events', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_events_pet_id'), 'scheduled_events', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_events_pet_id'), table_name='scheduled_events')
    op.drop_index(op.f('ix_scheduled_events_id'), table_name='scheduled_events')
    op.drop_index(op.f('ix_scheduled_events_due_date'), table_name='scheduled_events')
    op.drop_table('scheduled_events')
    sa.Enum(name='eventkind').drop(op.get_bind())
    # ### end Alembic commands ###
