"""Add language, unit system and currency to users

Revision ID: c8c383d27377
Revises: 70608dfc3c81
Create Date: 2026-08-25 06:38:59.785755

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8c383d27377'
down_revision: Union[str, Sequence[str], None] = '70608dfc3c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
    op.add_column('users', sa.Column('unit_system', sa.String(length=10), server_default='metric', nullable=False))
    op.add_column('users', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.drop_column('users', 'unit_system')
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
