"""Add pending_email to users

Revision ID: dbb56ee797f3
Revises: 677fca779bac
Create Date: 2026-08-21 23:52:33.041195

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dbb56ee797f3'
down_revision: Union[str, Sequence[str], None] = '677fca779bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
