"""add dietary restrictions and disabilities

Revision ID: e55d02345dcb
Revises: 8949430e0de7
Create Date: 2026-08-27 11:57:29.581457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55d02345dcb'
down_revision: Union[str, Sequence[str], None] = '8949430e0de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('dietary_restrictions', sa.ARRAY(sa.String(length=100)), server_default='{}', nullable=False))
    op.add_column('pets', sa.Column('disabilities', sa.ARRAY(sa.String(length=100)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'disabilities')
    op.drop_column('pets', 'dietary_restrictions')
    # ### end Alembic commands ###
