"""add pet photo

Revision ID: fc3b4e5234b8
Revises: 29d316c741e1
Create Date: 2026-08-10 05:35:22.902976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3b4e5234b8'
down_revision: Union[str, Sequence[str], None] = '29d316c741e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('photo_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'photo_filename')
    # ### end Alembic commands ###
